POST  http://localhost:3535/addpaciente
Content-Type: application/json

{
    "nome": "teste15",
    "cpf": "222.652.222-32",
    "sexo": "feminino",
    "idade": "55",
    "cod_paciente": "155688"
}

###
